### ISSUE TITLE
Correct Control Rig Link on README

### ISSUE THREAD

**Issue by ThePoetics** [catrone3/foundryvtt-shadowrunmacros#10]
Currently the README links to `https://github.com/catrone3/foundryvtt-shadowrunmacros/blob/main/Effect-Macros/catrone3/Control-Rig` when it should be `https://github.com/catrone3/foundryvtt-shadowrunmacros/tree/main/Effect-Macros/catrone3/Control%20rig`

**Comment by catrone3** [comment]
Will be fixed in next pr
