### ISSUE TITLE
[FeatureRequest] Macros to ask all players for a skill check

### ISSUE THREAD

**Issue by Stexinator** [catrone3/foundryvtt-shadowrunmacros#7]

**Comment by shadows-eye** [comment]
This would be cool if this could also be requested from a journal, that way request could be prepared

**Comment by Stexinator** [comment]
You can drag & drop macros to a journal page. So that would be feasible if the macro is constructed with the skill before hand. I was thinking about a dialog where you choose the skill. It would still work but have an extra step

**Comment by Stexinator** [comment]
A start where I tried to get it working was (await game.user.character.rollSkill("perception")) but that did not work as expected. Maybe it is helpful as it prompts the test but you cannot access the results

**Comment by catrone3** [comment]
I will look into this idea. I like it, although it may require the use of a module called Warp Gate. I will try it without that first

**Comment by catrone3** [comment]
Are you wanting this to be for any skill where you just specify it?

**Comment by shadows-eye** [comment]
Idea is that you write something like @Perception4 in the journal. Save the journal, then click on the perception and this will trigger the message to the chat with an action button for the players to click on. The action is preconfigured to be perception with a value to reach of 4 and will be a success if 4 or more are thrown. Each player can click on it to do the perception if needed 😀

And yes, any skill from the SR5 skill list.

**Comment by Stexinator** [comment]
I guess perception will be the most common one, so that is a good point to start. Determining the character will also be some work. You would need to check how many characters are in possession of the player and depending on that autoselect or provide a dropdown

**Comment by catrone3** [comment]
you want this in a journal? well that changes things. I already have a working macro that only has the issue of displaying the roll choice to the gm instead of the players. I will have it prompt for threshold so that it can display pass/fail easier.

**Comment by catrone3** [comment]
I have been digging through the foundry APIs and am not finding a way to send a dialog box to a target users screen. @Stexinator, if you happen to know how to do that with the Dialog command that would get this to a finished state

**Comment by Stexinator** [comment]
Send a message to chat with a button, which in turn renders the dialog. So only the player that click the button sees the dialog

**Comment by catrone3** [comment]
And how would I get that to work Stex? I am not a front end dev, I do backend and build scripts. The closest I have found is ChatMessage.create(). However that sanitizes any hooks or scripts I try to apply to based on what I have found with research. I could add another required module, but I want to limit that. So unless there is something in the sr5 system that can help with it I do not know how.

**Comment by catrone3** [comment]
I can not show dialog on the roll, but that would not allow any of the players to adjust any parts of the role should it be missing something, thinking modifiers from gear/abilities.

**Comment by catrone3** [comment]
Found out how to do this if I turn the entire repo into a module for foundry

**Comment by Stexinator** [comment]
You can also do it in a script. Its just more text and hooking gets unclean, so I would suggest doing it in a module.

For base principals you can look at a simple module I wrote to handle similiar cases: https://github.com/Stexinator/salvage-union-combat-automation/blob/main/src/scripts/weapons.js#L76

**Comment by Stexinator** [comment]
> I can not show dialog on the roll, but that would not allow any of the players to adjust any parts of the role should it be missing something, thinking modifiers from gear/abilities.

If you use the inbuild "rollSkill" the usual test window pops up. e.g : actor.rollSkill("perception")

**Comment by Stexinator** [comment]
For selecting one of multiple actors you would query all actors the user has, feed them to a options-element and return the value of the uuid. In the actual test you can use fromUUID to get the actor back. There is also an example in my module

**Comment by catrone3** [comment]
> For selecting one of multiple actors you would query all actors the user has, feed them to a options-element and return the value of the uuid. In the actual test you can use fromUUID to get the actor back. There is also an example in my module

This part I have already figured out, it was the button in the chat that I couldn't figure out. All of the examples I have seen and the documentation for what they call all need to have a template file for the render. The need of an outside file makes this something that either requires me to write a file (not sure a macro can do that) or make a module. And since I already have a request for making this repo a module I will go that route.

This will now be part of the work I am doing for #9
