### ISSUE TITLE
[FeatureRequest] Macro to go offline

### ISSUE THREAD

**Issue by Stexinator** [catrone3/foundryvtt-shadowrunmacros#8]
- make everything wireless turn off
- unequip (?) things that give wireless bonus
- maybe set a flag that the character is offline, which can be used in active effects to check (dont know if this works)

**Comment by catrone3** [comment]
I am not sure if this will be doable until there is a wireless flag available in the game system. although I can see what I can make work. the flag idea might work

**Comment by catrone3** [comment]
I can make a new flag. although It would need to be made on each matrix item, which outside of things like cyberware, decks, commlinks, and RCCs I am not sure of a way to grab all the other items easily

**Comment by Stexinator** [comment]
https://discord.com/channels/170995199584108546/1165811788948975648/1165901521582555136
