### ISSUE TITLE
[Feature Request] Format as installable Foundry module

### ISSUE THREAD

**Issue by ian612** [catrone3/foundryvtt-shadowrunmacros#9]
It would be nice to have this repository set up as a module that would include all the macros in a compendium that could be easily installed and updated by users.

**Comment by catrone3** [comment]
Having never done that, I will have to look it up. but I do like the idea, especially as it would allow the requirement of other modules to be handled by foundry

**Comment by catrone3** [comment]
Also not sure if that would work for the Effect Macros

**Comment by shadows-eye** [comment]
Should work the same way, world and Modul macros are the same.

**Comment by catrone3** [comment]
> Should work the same way, world and Modul macros are the same.

Even though they are macros inside of effects? I know you can't just drag and drop the macros into effect macro, you would have to copy the content of the macro.

**Comment by tjlanza** [comment]
Perhaps provide them as an Item in a Compendium with the AEs built in, but nothing else? That way, the end user would still need the original sources to complete them (to avoid issues regarding copyright and distribution of non-original IP), but the code would be in place.
